django/crud/boards/urls.py
from django.urls import path
from . import views # 현재 디렉토리의 views를 불러온다

#2개 이상의 앱에서, 동일한 url 별명을 구분하기 위해 app_name을 설정한다.
app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    #path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'), # variable routing 주소의 일정부분을 변수로 사용한다/ default:string이므로 int로 변환
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    #path('<int:pk>/update/', views.update, name='update'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/edit/', views.comments_edit, name='comments_edit'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

# 세번재 인자로 별명을 부여한다.
# --> 주소에 의존하지 않는다.
# --> 주소 변경이 용이하다.(다른곳에서는 별명을 사용하므로 urls.py에서만 변경하면 된다.)

django/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/crud/boards/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ProcessedImageField
from imagekit.processors import Thumbnail

def board_image_path(instance, filename):
    return f'boards/{instance.pk}번글/images/{filename}'

class Board(models.Model): # Board class는 models.Model을 상속받는다
    title = models.CharField(max_length=10) # 최대 글자수 10 / TextField사용 --> 무제한
    contents = models.TextField()
    image = ProcessedImageField(
        upload_to=board_image_path,  # 저장위치
        processors=[Thumbnail(200, 300)],
        format='JPEG',
        options={'quality': 90},  # 원본이미지의 90프로 해상도
    )
    created_at = models.DateTimeField(auto_now_add=True) # auto_now_add=True: 최초 그 값을 insert할 때 한번만 생성
    updated_at = models.DateTimeField(auto_now=True) # 게시글 수정시간 변경

    def __str__(self):
        return f'{self.id}번글 - {self.title} : {self.contents}'

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE) # on_delete=models.CASCADE: 게시글 지워지면 달려있는 댓글 같이 지워지도록

    def __str__(self):
        return f'<Board{self.board_id}: Comment({self.id} - {self.content})>'

django/crud/boards/views.py
from django.shortcuts import render, redirect
from .models import Board, Comment

def index(request):

    boards = Board.objects.all()[::-1]
    context = {'boards':boards}
    return render(request, 'boards/index.html', context)

def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        board = Board(title=title, contents=content, image=image)
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        return render(request, 'boards/new.html')

#def create(request):
#    # GET방식은 db에 접근이 가능하여 create에서 수정해도 수정된 글이 남게된다.
#    title = request.POST.get('title')
#    content = request.POST.get('content')
#
#    # 받아온 title, content를 DB에 저장
#    # 1. from .models import Board 현재 디렉토리의 models.py에서 Board class import
#    board = Board(title=title, contents=content)
#    board.save()
#
#    # redirect:
#    #return redirect(f'/boards/{board.pk}/')
#    return redirect('boards:detail', board.pk)

def detail(request, board_pk):
    board = Board.objects.get(pk=board_pk)

    comments = board.comment_set.all()
    # comments = Comment.objects.filter(comment.board.pk=board_pk)
    context = {'board':board, 'comments':comments}
    return render(request, 'boards/detail.html', context)

def delete(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.delete()
        #return redirect('/boards/')
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)

def edit(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.title = request.POST.get('title')
        board.contents = request.POST.get('contents')
        board.image = request.FILES.get('image')
        board.save()
        # return redirect(f'/boards/{board.pk}/')
        return redirect('boards:detail', board.pk)
    else:
        context = {'board': board}
        return render(request, 'boards/edit.html', context)

# def update(request, pk):
#     board = Board.objects.get(pk=pk)
#     board.title = request.POST.get('title')
#     board.contents = request.POST.get('contents')
#     board.save()
#     #return redirect(f'/boards/{board.pk}/')
#     return redirect('boards:detail', board.pk)

def comments_create(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        comment = Comment()
        comment.board_id = board.pk
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:detail', board.pk)

def comments_edit(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('boards:detail', board_pk)
    else:
        context = {'comment':comment}
        return render(request, 'boards/comments_edit.html', context)

def comments_delete(request, board_pk, comment_pk):
    if request.method == 'POST':
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
        return redirect('boards:detail', board_pk)
    else:
        return redirect('boards:detail', board_pk)

django/crud/boards/templates/boards/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="short icon" href="{% static 'boards/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'boards/favicon/favicon.ico' %} " type="image/x-icon">
    <title>Document</title>
</head>
<body>
    <img src="{% static 'CAT.jpg' %}" alt="cat">
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

django/crud/boards/templates/boards/comments_edit.html
{% extends 'boards/base.html' %}

{% block body %}
    <h1 class="text-center">Comment Edit</h1>
    <hr>
    <form action="{% url 'boards:comments_edit' comment.board.pk comment.pk %}" method="POST">
        {% csrf_token %}
        댓글 수정: <input type="text" name="content" value="{{ comment.content }}">
        <input type="submit" value="Submit">
    </form>

{% endblock %}

django/crud/boards/templates/boards/create.html
{% extends 'boards/base.html' %}

{% block body %}
<p>글이 정상적으로 작성되었습니다.</p>
{% endblock %}

django/crud/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% load static %}

{% block body %}
<h1 class="text-center">DETAIL</h1>
<h2>{{ board.pk }}번째 글</h2><hr>
    <p>글 제목: {{ board.title }}</p>
    <p>글 내용: {{ board.contents }}</p>
    <p>작성시간: {{ board.created_at }}</p>
    <p>수정시간: {{ board.updated_at }}</p>
    <hr>

    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        댓글: <input type="text" name="content">
        <input type="submit" value="댓글작성">
    </form>

    <hr>
        <p><b>댓글 목록 | 현재 댓글 개수: {{ comments|length }}</b></p>
        {% for comment in comments %}
            <li>{{ comment.content }}</li>
            <a href="{% url 'boards:comments_edit' board.pk comment.pk %}">[댓글 수정]</a>
            <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        {% empty %}
            <p><b>댓글 없음</b></p>
    <hr>
        {% endfor %}
    <hr>
    {% if board.image %}
        <h3>원본이미지</h3>
            <img src="{{ board.image.url }}" alt="{{ board.image }}">
        <h3>썸네일 이미지</h3>
            <img src="{{ board.image_thumbnail.url }}" alt="{{ board.image_thumbnail }}">
    {% endif %}
    <hr>
    <form action="{% url 'boards:delete' board.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="[글 삭제]">
    </form>
    <a href="{% url 'boards:edit' board.pk %}">[글 수정]</a><br>
    <a href="{% url 'boards:index' %}">[메인페이지]</a>
{% endblock %}

django/crud/boards/templates/boards/edit.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">EDIT</h1>
<hr>
    <p><b>기존 이미지</b></p>
    {% if board.image %}
        <img src="{{ board.image.url }}" alt="{{ board.image }}">
    {% endif %}
<hr>
<form action=""  method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    <label for="title">Title</label>
    <input type="text" name="title" id="title" value="{{ board.title }}"><br>
    <label for="content">Content</label><br>
    <textarea name="contents" id="contents" cols="30" rows="10">{{ board.contents }}</textarea><br>

    <label for="image">Image</label><br>
    <input type="file" name="image" id="image" accept="image/*"><br>

    <input type="submit" value="Submit">
</form>
<a href="{% url 'boards:index' %}">[메인 페이지]</a> <!-- 메인 페이지로 이동(index.html) -->
{% endblock %}

django/crud/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% load static %}

{% block body %}
<h1 class="text-center">Boards</h1>  <!-- class="text-center": 가운데 정렬 -->
<img src="{% static 'boards/images/DOG.jpg' %}" alt="">
<hr>
{% for board in boards %}
    글 번호:<p>{{ board.pk }}</p><br>
    글 제목:<p>{{ board.title }}</p><br>
    <!-- <a href="/boards/{{ board.pk }}">[글 상세 보기]</a> -->
    <a href="{% url 'boards:detail' board.pk %}">[글 상세 보기]</a>
    <hr>
{% endfor %}
<!-- <a href="/boards/new">[글작성]</a><br> -->
<a href="{% url 'boards:new' %}">[글작성]</a><br>
{% endblock %}

django/crud/boards/templates/boards/new.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">NEW</h1>
<hr>
<!-- <form action="{# url 'boards:create' #}" method="POST"> -->
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">Title</label> <!-- input 태그 라벨링 -->
    <input type="text" name="title" id="title"><br> <!-- label tag의 for와 input tag의 id 일치시켜야함 -->
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="30" rows="10"></textarea> <!-- input tag보다 큰 창 -->
    <label for="image">Image</label><br>
    <input type="file" name="image" id="image" accept="image/*"><br>
    <input type="submit" value="Submit">
</form>
<a href="{% url 'boards:index' %}">[메인 페이지]</a>
{% endblock %}