django/prac/movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:movie_pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
]

django/prac/prac/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

django/prac/movies/models.py
from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_origin = models.CharField(max_length=100)
    vote_count = models.IntegerField()
    open_date = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

django/prac/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

def index(request):
    movies = Movie.objects.all()[::-1]
    context = {'movies':movies}
    return render(request, 'movies/index.html', context)

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    context = {'movie':movie}
    return render(request, 'movies/detail.html', context)

def new(request):
    if request.method == 'POST':
        movie = Movie()
        movie.title = request.POST.get('title')
        movie.title_origin = request.POST.get('title_origin')
        movie.vote_count = request.POST.get('vote_count')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/new.html')

def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.title_origin = request.POST.get('title_origin')
        movie.vote_count = request.POST.get('vote_count')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        context = {'movie':movie}
        return render(request, 'movies/update.html', context)

def delete(request, movie_pk):
    if request.method == 'POST':
        movie = Movie.objects.get(pk=movie_pk)
        movie.delete()
        return redirect('movies:index')
    return redirect('movies:detail', movie_pk)

django/prac/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Movie-crud</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

django/prac/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% load static %}

{% block body %}
<h1 class="text-center">DETAIL</h1>
<hr>
<img src="{{ movie.poster_url }}" width="200" height="300" alt="poster">
<hr>
<p>
    <b>Title: </b>{{ movie.title }}<br>
    <b>Title_Origin: </b>{{ movie.origin }}<br>
    <b>Vote_Count: </b>{{ movie.vote_count }}<br>
    <b>Open_Date: </b>{{ movie.open_date }}<br>
    <b>Genre: </b>{{ movie.genre }}<br>
    <b>Score: </b>{{ movie.score }}<br>
    <b>Description: </b>{{ movie.description }}<br>
</p>
<hr>
    <a href="{% url 'movies:index' %}">[목록]</a><br>
    <a href="{% url 'movies:update' movie.pk %}">[수정]</a><br>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="[삭제]">
    </form>

{% endblock %}

django/prac/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block body %}

<h1 class="text-center">Boards</h1>
<hr>
<a href="{% url 'movies:new' %}">[새 영화 등록]</a>
<hr>
{% for movie in movies %}
    <p>
        <a href="{% url 'movies:detail' movie.pk %}">Title: {{ movie.title }}</a><br>
        Score: <span>{{movie.score}}</span> <br>
<hr>
    </p>
{% endfor %}
<hr>


{% endblock %}

django/prac/movies/templates/movies/new.html
{% extends 'movies/base.html' %}

{% block body %}
<h1 class="text-center">NEW</h1>
<hr>

<form action="{% url 'movies:new' %}" method="POST">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title"><br>
    <label for="title_origin">Title_Origin</label><br>
    <input type="text" name="title_origin" id="title_origin"><br>
    <label for="vote_count">Vote_Count</label><br>
    <input type="number" name="vote_count" id="vote_count"><br>
    <label for="open_date">Open_Date</label><br>
    <input type="date" name="open_date" id="open_date"><br>
    <label for="genre">Genre</label><br>
    <input type="text" name="genre" id="genre"><br>
    <label for="score">Score</label><br>
    <input type="number" min="0" max="10" step="0.5" name="score" id="score"><br>
    <label for="poster_url">Poster_Url</label><br>
    <input type="text" name="poster_url" id="poster_url"><br>
    <label for="description">Description</label><br>
    <textarea name="description" id="description" cols="30" rows="10"></textarea><br>
    <input type="submit" value="Submit">
</form>

{% endblock %}

django/prac/movies/templates/movies/update.html
{% extends 'movies/base.html' %}

{% block body %}
<h1 class="text center">EDIT</h1>
<hr>
<form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title" value="{{ movie.title }}"><br>
    <label for="title_origin">Title_Origin</label><br>
    <input type="text" name="title_origin" id="title_origin" value="{{ movie.title_origin }}"><br>
    <label for="vote_count">Vote_Count</label><br>
    <input type="number" name="vote_count" id="vote_count" value="{{ movie.vote_count }}"><br>
    <label for="open_date">Open_Date</label><br>
    <input type="date" name="open_date" id="open_date" value="{{ movie.open_date }}"><br>
    <label for="genre">Genre</label><br>
    <input type="text" name="genre" id="genre" value="{{ movie.genre }}"><br>
    <label for="score">Score</label><br>
    <input type="number" name="score" id="score" value="{{ movie.score }}"><br>
    <label for="poster_url">Poster_Url</label><br>
    <input type="text" name="poster_url" id="poster_url" value="{{ movie.poster_url }}"><br>
    <label for="description">Description</label><br>
    <textarea name="description" id="description" cols="30" rows="10">{{ movie.description }}</textarea><br>
    <input type="submit" value="Submit">
</form>

{% endblock %}