django/myform/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.change_password, name='change_password'),
]

django/myform/boards/urls.py
from django.urls import path
from . import views

app_name='boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:board_pk>/like/', views.like, name='like'),
    path('<int:board_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

django/myform/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

django/myform/boards/models.py
from django.db import models
from django.conf import settings

class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_boards', blank=True) #blank=True: 좋아요를 누르지 않으면 빈 값을 넣어준다.

    def __str__(self):
        return f'글 번호 -> {self.id}, 글 제목 -> {self.title}, 글 내용 -> {self.content}'

class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    class Meta:
        ordering = ('-pk',) # 최신 댓글이 위에 오도록

django/myform/boards/forms.py
from django import forms
from .models import Board
from .models import Comment

class BoardForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        max_length=10,
        widget=forms.TextInput(attrs={
            'class':'title',
            'placeholder':'Enter the title'
        })
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(attrs={
            'class':'content-type',
            'rows':5,
            'cols':50,
            'placeholder':'Enter the content'
        })
    )
    class Meta:
        model = Board
        fields = ['title', 'content',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]



# class BoardForm(forms.Form):s
#     title = forms.CharField(
#         max_length=10,
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'class':'title',
#                 'placeholder':'Enter the title',
#             }
#         )
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class':'content-type',
#                 'rows':5,
#                 'cols':50,
#                 'placeholder':'Enter the content',
#             }
#         )
#     )

django/myform/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from IPython import embed
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model


def index(request):
    boards = Board.objects.all()[::-1]
    context = {'boards':boards}
    return render(request, 'boards/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
       form = BoardForm(request.POST) # 사용자가 create.html에서 날린 데이터를
       #embed()
       if form.is_valid(): # form이 유효하면(is_vaild: 유효성 검사--> boolean값 리턴)
           board = form.save(commit=False) #commit=False: 저장 보류
           board.user = request.user #request.user: 로그인된 user 정보/ board.user: board class의 user field
           board.save()
           # title = form.cleaned_data.get('title') # .cleaned_data: 정제하여 dict 형태로
           # content = form.cleaned_data.get('content')
           # board = Board.objects.create(title=title, content=content) # .create(): .save() 필요없음
           return redirect('boards:detail', board.pk)
    else:
        form = BoardForm()
    context = {'form':form}
    return render(request, 'boards/form.html', context)

def detail(request, board_pk):
    #board = Board.objects.get(pk=board_pk)
    board = get_object_or_404(Board, pk=board_pk) # Board에 해당하는 pk있으면 가져오고, 없으면 404 error 띄운다
    person = get_object_or_404(get_user_model(), pk=board.user.pk)
    comments = board.comment_set.all()
    comment_form = CommentForm()
    context = {'board': board, 'comments':comments, 'comment_form':comment_form, 'person':person,}
    return render(request, 'boards/detail.html', context)

def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method =='POST':
            board.delete()
            return redirect('boards:index')
        else:
            return redirect('boards:detail', board_pk)
    else:
        return redirect('boards/index')

@login_required
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method == 'POST':
            form = BoardForm(request.POST, instance=board)
            if form.is_valid():
                form.save()
                # board.title = form.cleaned_data.get('title')
                # board.content = form.cleaned_data.get('content')
                # board.save()
                return redirect('boards:detail', board_pk)
        else:
            #form = BoardForm(initial=board.__dict__) # initial=board.__dict__: 초기값의 정보 제공/ board를 dict 형태로 전달
            form = BoardForm(instance=board)
    else:
        return redirect('boards:index')
    context = {'form':form, 'board':board}
    return render(request, 'boards/form.html', context)

@login_required
@require_POST # POST요청 이외의 요청이 들어오면 405 error 띄운다.
def comments_create(request, board_pk):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False) # user 정보 필요하므로 잠시 hold
        comment.user = request.user # comment.user에 요청자의 정보를 넣는다
        comment.board_id = board_pk
        comment.save()
        return redirect('boards:detail', board_pk)

@login_required
@require_POST
def comments_delete(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user != comment.user:
        return redirect('boards:detail', board_pk)
    else:
        comment.delete()
        return redirect('boards:detail', board_pk)

@login_required
def like(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    user = request.user

    if request.user in board.like_users.all():
    # if board.like_users.filter(pk=user.pk).exists: # 최소 하나의 값이 들어가 있는지 확인/ 게시글에 좋아요를 누른 유저가 존재한다면
        board.like_users.remove(request.user) # 좋아요 또 누르면 좋아요 취소(like_user에서 제거)
    else:
        board.like_users.add(request.user) # 게시글에 좋아요를 누른 유저 존재X --> 좋아요 누르면 like_users에 추가
    return redirect('boards:index')

@login_required
def follow(request, board_pk, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)

    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('boards:detail', board_pk)

django/myform/boards/templates/boards/_board.html
<div class="card-body">
    <a href="{% url 'boards:like' board.pk %}" class="card-link">
        {% if user in board.like_users.all %}
            <i class="fas fa-heart fa-lg" style="color:crimson"></i>
        {% else %}
            <i class="far fa-heart fa-lg" style="color:black"></i>
        {% endif %}
    </a>
    <p class="card-text">이 글을 {{ board.like_users.count }} 명이 좋아합니다.</p>
</div>

django/myform/boards/templates/boards/_profile.html
<div class="jumbotron text-center text-white bg-dark">
    <p class="lead mb-1">작성자 정보</p>
    <h2 class="display">{{ board.user }}</h2>
    <hr class="border-white">
    <p class="lead">
        팔로잉: {{ person.followings.all | length }}
        팔로워: {{ person.followers.all | length }}
    </p>
    {% if user != person %}
        {% if user in person.followers.all %}
            <!-- role="button": 시각장애인의 접근성 향상 -->
            <a class="btn btn-primary" href="{% url 'boards:follow' board.pk person.pk %}" role="button">Unfollow</a>
        {% else %}
            <a class="btn btn-primary" href="{% url 'boards:follow' board.pk person.pk %}" role="button">Follow</a>
        {% endif %}
    {% endif %}
</div>

django/myform/boards/templates/boards/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    {% bootstrap_css %}
    <title>Form Practice</title>
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
            <h1>안녕, {{ user.username }}</h1>
            <hr>
            <a href="{% url 'accounts:edit' %}">회원정보 수정</a><br>
            <a href="{% url 'accounts:change_password' %}">비밀번호 변경</a><br>
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="로그아웃">
            </form>
            <form action="{% url 'accounts:delete' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="회원탈퇴">
            </form>

        {% else %}
            <a href="{% url 'accounts:login' %}">[로그인]</a><br>
            <a href="{% url 'accounts:signup' %}">[회원가입]</a>
        {% endif %}
        <hr>
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

django/myform/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
    <h1 class="text-center">DETAIL</h1>
    <hr>

    <h2>{{ board.pk }}번글</h2>
        <p>글 제목: {{ board.title }}</p>
        <p>글 내용: {{ board.content }}</p>
        <p>글 작성 시각: {{ board.created_at }}</p>
        <p>글 수정 시각: {{ board.updated_at }}</p>
    <hr>
    <h3>댓글</h3>
        {% for comment in comments|dictsortreversed:'pk' %} <!-- |dictsortreversed:'pk': 최신 댓글이 위에 위치 하도록 -->
            <p><b>{{ comment.user }}님의 댓글: {{ comment.content }}</b></p>
            {% if user == comment.user %}
                <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="[댓글삭제]">
                </form>
            {% endif %}
        {% empty %}
            <p><b>댓글이 없습니다.</b></p>
        {% endfor %}
    <hr>

    {% include 'boards/_profile.html' %}

    <hr>
    <h3>댓글 작성</h3>
        {% if user.is_authenticated %}
            <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <input type="submit" value="댓글 작성">
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}">댓글 작성을 위해 로그인이 필요합니다</a><br>
        {% endif %}
        <a href="{% url 'boards:index' %}">[메인페이지]</a><br>
        {% if user == board.user %}
            <a href="{% url 'boards:update' board.pk %}">[수정]</a><br>
            <form action="{% url 'boards:delete' board.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="[삭제]">
        {% endif %}
            </form>
{% endblock %}

django/myform/boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %} <!-- url name이 create일 때, -->
    <h1 class="text-center">CREATE</h1>
{% else %}
    <h1 class="text-center">UPDATE</h1>
{% endif %}
<hr>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button "글작성" button_type='submit' button_class='btn_primary' %}
    <!-- {{ form.as_p }} --> <!-- form을 p태그로 감싸겠다 -->
    <!-- <input type="submit" value="Submit"> -->
</form>
{% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'boards:index' %}" class="btn btn-danger">메인페이지</a> <!-- danger:red -->
{% else %}
    <a href="{% url 'boards:detail' board.pk %}" class="btn btn-primary">뒤로가기</a> <!-- primary:blue -->
{% endif %}
{% endblock %}

django/myform/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">INDEX</h1>
<hr>
    {% for board in boards %}
        <p><b>글 작성자: {{ board.user }}</b></p>
        <p>글 번호: {{ board.pk }}</p>
        <p>글 제목: {{ board.title }}</p>
        <a href="{% url 'boards:detail' board.pk %}">[글 상세보기]</a><br>
        {% include 'boards/_board.html' %}
        <hr>
    {% endfor %}

    {% if user.is_authenticated %}
        <a href="{% url 'boards:create' %}">[글 작성]</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">[글을 작성하려면 로그인 해주세요]</a>
    {% endif %}
{% endblock %}