django/crud_practice/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/update/', views.update, name='update'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

django/crud_practice/crud_practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

django/crud_practice/boards/models.py
from django.db import models

class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

django/crud_practice/boards/views.py
from django.shortcuts import render,redirect
from .models import Board, Comment

def index(request):
    boards = Board.objects.all()[::-1]
    context = {'boards':boards}
    return render(request, 'boards/index.html', context)

def create(request):
    board = Board()
    if request.method == 'POST':
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:index')
    else:
        return render(request, 'boards/new.html')


def detail(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    comments = board.comment_set.all()
    context = {'board':board, 'comments':comments}
    return render(request, 'boards/detail.html', context)

def update(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail', board_pk)
    else:
        context = {'board': board}
        return render(request, 'boards/edit.html', context)


def delete(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board_pk)

def comments_create(request, board_pk):
    comment = Comment()
    print(request.POST.get('content'))
    comment.content = request.POST.get('content')
    comment.board_id = board_pk
    comment.save()
    return redirect('boards:detail', board_pk)

def comments_update(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('boards:detail', board_pk)
    else:
        context = {'comment': comment}
        return render(request, 'boards/comments_edit.html', context)


def comments_delete(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)
    else:
        return redirect('boards:detail', board_pk)

django/crud_practice/boards/templates/boards/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

django/crud_practice/boards/templates/boards/comments_edit.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">Comments Edit</h1>
    <form action="{% url 'boards:comments_update' comment.board.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="text" name="content" value="{{ comment.content }}">
        <input type="submit" value="댓글수정">
    </form>


{% endblock %}

django/crud_practice/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">DETAIL</h1>
<hr>
    글 제목: {{ board.title }}<br>
    글 내용: {{ board.content }}<br>
    작성 시각: {{ board.created_at }}<br>
    수정 시각: {{ board.updated_at }}<br>
<hr>
    <p><b>댓글</b>
        <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
            <input type="text" name="content">
            <input type="submit" value="댓글작성">
        </form>
        {% for comment in comments %}
            {{ comment.content }}<br>
            <a href="{% url 'boards:comments_update' board.pk comment.pk %}">댓글수정</a><br>
            <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="댓글삭제">
            </form>
        {% endfor %}
    </p>
<hr>
    <a href="{% url 'boards:index' %}">[메인페이지]</a><br>
    <a href="{% url 'boards:update' board.pk %}">[글 수정]</a><br>
    <form action="{% url 'boards:delete' board.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글 삭제">
    </form>
<hr>
{% endblock %}

django/crud_practice/boards/templates/boards/edit.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">EDIT</h1>
<hr>
    <form action="{% url 'boards:update' board.pk %}" method="POST">
        {% csrf_token %}
        <label for="title">Title</label><br>
        <input type="text" name="title" value="{{ board.title }}"><br>
        <label for="content">Content</label><br>
        <textarea name="content" id="content" cols="30" rows="10">{{ board.content }}</textarea><br>
        <input type="submit" value="Submit">
    </form>


{% endblock %}

django/crud_practice/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">Boards</h1>
<hr>
{% for board in boards %}
    <p>
        글 번호: {{ board.pk }}<br>
        글 제목: {{ board.title }}<br>
        <a href="{% url 'boards:detail' board.pk %}">[글 상세보기]</a>
        <hr>
    </p>
{% endfor %}

<a href="{% url 'boards:create' %}">[글 작성]</a>

{% endblock %}

django/crud_practice/boards/templates/boards/new.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">NEW</h1>
<hr>
<form action="{% url 'boards:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title"><br>
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
    <input type="submit" value="Submit">
</form>


{% endblock %}